;;;; synonym-data.lisp

(in-package #:net.bti.fuzzy-search)

;;; ----------------------------------------------------------------------------

(a:define-constant +person-given-name-synonyms+ '(("DANIEL" "DAN" "DANNY")
                                                  ("WILLIAM" "WILL" "BILL" "BILLY" "LIAM")
                                                  ("ROBERT" "ROB" "BOB" "BOBBY" "ROBBIE")
                                                  ("RICHARD" "RICK" "RICKY" "DICK" "DICKEY")
                                                  ("THOMAS" "TOM" "TOMMY")
                                                  ("EDWARD" "ED" "EDDIE" "TED" "TEDDY" "NED")
                                                  ("JOHN" "JON" "JOHNNY")
                                                  ("CHARLES" "CHARLIE" "CHUCK")
                                                  ("JAMES" "JIM" "JIMMY")
                                                  ("STEPHEN" "STEVE" "STEVIE")
                                                  ("ANDREW" "ANDY" "DREW")
                                                  ("NICHOLAS" "NICK" "NICKY")
                                                  ("ANTHONY" "TONY")
                                                  ("MICHAEL" "MIKE" "MICKEY")
                                                  ("PATRICK" "PAT" "PADDY")
                                                  ("KENNETH" "KEN" "KENNY")
                                                  ("JONATHAN" "JOHN" "JON" "JONNY")
                                                  ("MATTHEW" "MATT" "MATTY")
                                                  ("ALEXANDER" "ALEX" "XANDER" "SANDY")
                                                  ("BENJAMIN" "BEN" "BENNY")
                                                  ("SAMUEL" "SAM" "SAMMY")
                                                  ("JOSEPH" "JOE" "JOEY")
                                                  ("FRANCIS" "FRANK" "FRANKIE")
                                                  ("GEORGE" "GEORGIE")
                                                  ("JACOB" "JAKE")
                                                  ("HENRY" "HANK" "HARRY")
                                                  ("CHRISTOPHER" "CHRIS" "KIT")
                                                  ("TIMOTHY" "TIM" "TIMMY")
                                                  ("LAWRENCE" "LARRY" "LAURIE")
                                                  ("GREGORY" "GREG" "GREGG")
                                                  ("FREDERICK" "FRED" "FREDDIE")
                                                  ("DONALD" "DON" "DONNIE")
                                                  ("JEREMY" "JERRY")
                                                  ("JEFFREY" "JEFF" "JEFFY")
                                                  ("RONALD" "RON" "RONNIE")
                                                  ("ERIC" "RICK" "RICO")
                                                  ("PHILIP" "PHIL")
                                                  ("ARTHUR" "ART" "ARTY")
                                                  ("STANLEY" "STAN")
                                                  ("RAYMOND" "RAY")
                                                  ("ADAM" "ADE")
                                                  ("PETER" "PETE")
                                                  ("MARK" "MARC")
                                                  ("BRIAN" "BRY")
                                                  ("ALBERT" "AL" "ALBIE")
                                                  ("ALLEN" "AL" "ALLY")
                                                  ("DENNIS" "DEN" "DENNY")
                                                  ("LEONARD" "LEN" "LENNY")
                                                  ("HAROLD" "HAL" "HARRY")
                                                  ("VINCENT" "VINCE" "VINNY")
                                                  ("DOUGLAS" "DOUG" "DOUGIE")
                                                  ("RUSSELL" "RUSS")
                                                  ("GARY" "GAZ")
                                                  ("STEVEN" "STEVE" "STEVIE")

                                                  ;; Female names
                                                  ("ELIZABETH" "LIZ" "LIZZY" "BETH" "BETTY" "ELIZA" "LISA" "ELLIE")
                                                  ("CATHERINE" "CATHY" "KATE" "KATY" "KATIE" "CAT")
                                                  ("KATHERINE" "KATE" "KATY" "KATHY" "KATIE")
                                                  ("MARGARET" "MAGGIE" "MEG" "PEGGY" "MARGE" "GRETA" "MARGO")
                                                  ("REBECCA" "BECKY" "BECCA")
                                                  ("JENNIFER" "JEN" "JENNY")
                                                  ("JESSICA" "JESS" "JESSIE")
                                                  ("PATRICIA" "PAT" "PATTY" "TRISH" "TRICIA")
                                                  ("BARBARA" "BARB" "BARBIE" "BABS")
                                                  ("DEBORAH" "DEBBIE" "DEB" "DEBORA")
                                                  ("CHRISTINA" "CHRIS" "CHRISSY" "TINA")
                                                  ("SUSAN" "SUE" "SUSIE" "SUZIE")
                                                  ("KIMBERLY" "KIM" "KIMMIE")
                                                  ("AMANDA" "MANDY" "AMY")
                                                  ("MELISSA" "MEL" "MELLY" "LISSY")
                                                  ("RACHEL" "RACH" "RAY")
                                                  ("SARAH" "SALLY" "SADIE")
                                                  ("HEATHER" "HEATH" "HETTY")
                                                  ("LAURA" "LAURIE" "LORRIE")
                                                  ("MICHELLE" "SHELLY" "SHELL" "CHELLE")
                                                  ("STEPHANIE" "STEFFI" "STEFF" "ANNIE")
                                                  ("KAREN" "KARI" "KAZ")
                                                  ("LINDA" "LINDY")
                                                  ("CYNTHIA" "CINDY")
                                                  ("ANGELA" "ANGIE")
                                                  ("NICOLE" "NICKY" "NIKKI")
                                                  ("VICTORIA" "VICKY" "VICKI" "TORI")
                                                  ("ALLISON" "ALLY" "ALLIE")
                                                  ("RUTH" "RUTHIE")
                                                  ("ANNE" "ANN" "ANNIE" "NANCY")
                                                  ("CAROLINE" "CARRIE" "CAROL" "CARO")
                                                  ("THERESA" "TESS" "TESSA" "TERI" "TRACEY")
                                                  ("MARGARETTA" "GRETA" "MARGO" "RITA")
                                                  ("MARILYN" "MARY" "LYNN")
                                                  ("NATALIE" "NAT" "NATTY")
                                                  ("ISABELLA" "BELLA" "IZZY" "BELLE" "ISA")
                                                  ("SOPHIA" "SOPHIE")
                                                  ("ALEXANDRA" "ALEX" "LEXI" "SANDY")
                                                  ("EMILY" "EM" "EMMY")
                                                  ("ABIGAIL" "ABBIE" "ABBY")
                                                  ("OLIVIA" "LIV" "LIVVY")
                                                  ("HANNAH" "HAN" "HANNIE")
                                                  ("GRACE" "GRACIE")
                                                  ("CHLOE" "CLO")
                                                  ("MEGAN" "MEG" "MEGGIE")
                                                  ("KELLY" "KEL" "KELS")
                                                  ("TAYLOR" "TAY" "TAYTAY")
                                                  ("BROOKLYN" "BROOKE")
                                                  ("COURTNEY" "COURT")
                                                  ("JULIA" "JULIE" "JULES")
                                                  ("KATHERINA" "KAT" "KATYA")
                                                  ("MADISON" "MADDIE" "MADDY")
                                                  ("SAVANNAH" "SAV" "VANNA")
                                                  ("HAILEY" "HAILS")
                                                  ("AUBREY" "BREY" "AUBS")
                                                  ("BRITTANY" "BRITT" "BRIT")
                                                  ("ASHLEY" "ASH" "ASHY")
                                                  ("RILEY" "RY" "RILES")
                                                  ("PAIGE" "PAIGEY")
                                                  ("AMY" "AMES")
                                                  ("LAUREN" "LAUR" "LAURIE")
                                                  ("ERICA" "RICA" "ERI")
                                                  ("CASSANDRA" "CASSIE" "SANDRA" "CASS")
                                                  ("TAMARA" "TAMMY" "MARA")
                                                  ("KATRINA" "KAT" "KATIE")
                                                  ("LILLIAN" "LILY" "LILLY" "LIL")
                                                  ("ELEANOR" "ELLIE" "NORA" "LENORE")
                                                  ("MARTHA" "MARTY" "MATTIE")
                                                  ("JACQUELINE" "JACKIE" "JACQUI")
                                                  ("ROSEMARY" "ROSE" "ROSIE" "ROMY")
                                                  ("ALICIA" "ALLY" "LISHA")
                                                  ("DANIELLE" "DANNI" "DANI")

                                                  ;; Unisex / phonetic
                                                  ("ALEX" "ALEC" "ALIX")
                                                  ("JORDAN" "JORDEN" "JORDYN" "JORDANN")
                                                  ("CASEY" "KASEY" "KAYCE" "KACEY")
                                                  ("TAYLOR" "TAYLOR" "TAYLORR" "TAYLUR" "TAYLAR")
                                                  ("MORGAN" "MORGHAN" "MORGYN")
                                                  ("JAMIE" "JAYMIE" "JAYME" "JAMI" "JAMEY")
                                                  ("CAMERON" "CAM" "KAMERON" "KAM")
                                                  ("DREW" "ANDREW")
                                                  ("RILEY" "RYLEY" "RYLEIGH" "RILEE" "RILEY-JANE")
                                                  ("RYAN" "RYANN" "RYANE" "RYEN")
                                                  ("AUBREY" "AUBRI" "AUBREE" "AUBRIE" "OBRI")
                                                  ("SKYLER" "SKYLAR" "SKYE")
                                                  ("DEVON" "DEVIN" "DEVEN" "DEVEN" "DEVYNN")
                                                  ("DALLAS" "DALAS" "DALLIS")
                                                  ("HUNTER" "HUNT" "HUNTA")
                                                  ("JESSE" "JESSI" "JESSY" "JESSEE")
                                                  ("KENDALL" "KENDEL" "KENDYL" "KENDAHL")
                                                  ("KELLY" "KELLI" "KELLEE" "KELLEIGH" "KELLYE")
                                                  ("REESE" "RHYS" "REES")
                                                  ("PARKER" "PARKE" "PARQER")
                                                  ("QUINN" "QUIN" "QUYNN" "QUYN")
                                                  ("ROBIN" "ROBYN")
                                                  ("CHARLIE" "CHARLEY" "CHARLEE" "CHARLI")
                                                  ("SAM" "SAMMY" "SAMMIE")
                                                  ("JODY" "JODIE" "JODI" "JODIEE")
                                                  ("PAT" "PATT" "PADDY")
                                                  ("LEE" "LEIGH" "LEA" "LEEY")
                                                  ("DANA" "DAYNA" "DANAH" "DANAE")
                                                  ("TERRY" "TERRI" "TERI" "TERRIE")
                                                  ("ALEXIS" "LEXI" "LEXIE" "ALEXA" "ALEXYSS")
                                                  ("BAILEY" "BAILEE" "BAILIE" "BAYLEE")
                                                  ("ADDISON" "ADDY" "ADDIE" "ADY")
                                                  ("BROOKE" "BROOK" "BROOKLYN" "BROOKLYNN" "BROOKLIN")
                                                  ("ROWAN" "ROWEN" "ROAN" "ROEN")
                                                  ("EMERY" "EMORY" "EMMERY" "EMMORY")
                                                  ("PAYTON" "PEYTON" "PAYTEN" "PAYTIN")
                                                  ("FINLEY" "FINLEE" "FINLAY" "FINLAYE")
                                                  ("HARLEY" "HARLIE" "HARLLEE" "HARLEE")
                                                  ("REEGAN" "REGAN" "REAGAN" "REYGAN")
                                                  ("ALEXANDER" "ALEXANDRA" "ALEX" "ALEXX" "ALEKS" "ALEC" "ALEK")
                                                  ("FRANKIE" "FRANCIE" "FRANKEE")
                                                  ("ELLIOTT" "ELIOT" "ELIOTT" "ELIOTTE")
                                                  ("LOGAN" "LOGANN" "LOGEN" "LOAGAN")
                                                  ("MICAH" "MIKA" "MYCA" "MYKAH")
                                                  ("NOEL" "NOELLE" "NOELE" "NOELLA")
                                                  ("TATE" "TATUM" "TAYTE")
                                                  ("CHRIS" "KRIS" "KRISS" "CHRISS" "KRYS")
                                                  ("KIM" "KIMM" "KIMMIE" "KYM" "KYMIE")
                                                  ("NIKKI" "NICKY" "NIKI" "NICCI" "NIKKIE" "NICKIE")
                                                  ("JAY" "JAE" "JAYE" "JAYY")
                                                  ("MAX" "MAXIE" "MAXI" "MAXX" "MAXXIE")
                                                  ("BLAKE" "BLAIK" "BLAIKKE")
                                                  ("TOMMY" "TOMMIE" "TOMI")
                                                  ("RAY" "REY" "RAE" "RAEY")
                                                  ("CHANDLER" "CHANDLAR" "CHANDLERZ")
                                                  ("DILLON" "DYLAN" "DILAN" "DILYN" "DILLAN")
                                                  ("SEAN" "SHAWN" "SHAUN" "SHON" "SHAWNIE")
                                                  ("BRADLEY" "BRAD" "BRADY")
                                                  ("CORY" "COREY" "KORY" "KOREY")
                                                  ("LEE" "LEIGH" "LEA")
                                                  ("JACKSON" "JAX" "JAXON" "JAXEN")
                                                  ("ELLIS" "ELLISSE" "ELLYS")
                                                  ("RYLEE" "RYLEIGH" "RYLEA")
                                                  ("CASE" "CAYCE" "CAYCEE")
                                                  ("KAI" "KYE" "KY")
                                                  ("PHOENIX" "FENIX")
                                                  ("ROWEN" "ROWAN")
                                                  ("SAWYER" "SAWYE")
                                                  ("SAGE" "SAIGE")
                                                  ("RIVER" "RIVERR" "RIVAH")
                                                  ("DARCY" "DARCEY" "DARSEY")
                                                  ("INDI" "INDY" "INDIE")
                                                  ("ASH" "ASHLYN" "ASHTON" "ASHLEE" "ASHLEIGH")
                                                  ("REMINGTON" "REM" "REMI" "REMY")
                                                  ("EVAN" "EVIN" "EVANN" "EVYN")
                                                  ("AUSTIN" "AUSTYN" "AUSTEN")
                                                  ("COREY" "KOREY" "CORI")
                                                  ("CAM" "KAM" "CAMI")
                                                  ("RORY" "RORI" "RORIE")
                                                  ("JAYDEN" "JADEN" "JAYDYN" "JADYN" "JAYDON")
                                                  ("AARON" "ERIN" "ARON" "ARRON")
                                                  ("BILLY" "BILLIE")
                                                  ("TONY" "TONI")
                                                  ("ROB" "ROBYN" "ROBBIE")
                                                  ("JOE" "JOEY" "JOEY-JO")
                                                  ("ANDY" "ANDI" "ANDIE")
                                                  ("FRANCIS" "FRANCES" "FRANKIE" "FRAN")
                                                  ("LOU" "LOUIE" "LOUISE" "LOUISA")
                                                  ("GERRY" "JERRY" "GERI" "GERY")
                                                  ("MICHAEL" "MICHEAL" "MICK" "MIKEY" "MIKAL" "MICAEL")
                                                  ("STEPHEN" "STEVEN" "STEVE" "STEVIE" "STEFAN" "STEFANIE")
                                                  ("GEORGE" "GEORGIA" "GEORGIE")
                                                  ("HARRY" "HARRIET" "HARRI")
                                                  ("DANNY" "DANI" "DANIE" "DANNIE")
                                                  ("CHARLIE" "CHARLOTTE" "CHARLEE" "CHARLI")
                                                  ("BOBBY" "BOBBI" "BOBBIE")
                                                  ("JAMIE" "JAMES" "JAMEY")
                                                  ("RAY" "RAE" "RAYE")
                                                  ("SAMMY" "SAMMIE")
                                                  ("LEE" "LEIGH" "LEA")
                                                  ("KERRY" "CARRIE" "KERRI")
                                                  ("TERRY" "TERI" "TERRI")
                                                  ("TRACY" "TRACEY" "TRACI" "TRACIE"))
  :test #'equalp)

(a:define-constant +address-synonyms+ '(("AVENUE" "AVE" "AV" "AVN" "AVEN" "AVENU")
                                        ("STREET" "ST" "STR" "STRT")
                                        ("ROAD" "RD")
                                        ("BOULEVARD" "BLVD" "BOUL" "BOULV")
                                        ("DRIVE" "DR" "DRV" "DRIV")
                                        ("COURT" "CT" "CRT")
                                        ("CIRCLE" "CIR" "CIRC" "CRCL" "CIRCL")
                                        ("LANE" "LN" "LNE")
                                        ("PLACE" "PL" "PLC")
                                        ("SQUARE" "SQ" "SQR" "SQRE")
                                        ("TERRACE" "TER" "TERR" "TERRC")
                                        ("TRAIL" "TRL" "TR")
                                        ("WAY" "WY" "WA" "WYA")
                                        ("HIGHWAY" "HWY" "HIGHWY" "HIWAY" "HIWY" "HY")
                                        ("PARKWAY" "PKWY" "PARKWY" "PKY" "PKWAY")
                                        ("DRIVEWAY" "DRWY" "DRIVEWY")
                                        ("EXPRESSWAY" "EXPY" "EXPWY" "EXP" "EXPR" "EXPRESSWY")
                                        ("FREEWAY" "FWY" "FRWY" "FREEWY")
                                        ("TURNPIKE" "TPKE" "TRNPK" "TURNPK")
                                        ("CAUSEWAY" "CSWY" "CAUSWY")
                                        ("CROSSING" "XING" "CRSG" "CRSSNG")
                                        ("ALLEY" "ALY" "ALLY")
                                        ("PLAZA" "PLZ" "PLZA")
                                        ("CENTER" "CTR" "CNTR" "CEN" "CENT" "CENTR" "CENTRE")
                                        ("RIDGE" "RDG" "RDGE")
                                        ("BRIDGE" "BRG" "BRDGE")
                                        ("MOUNT" "MT" "MNTA" "MTN" "MNT")
                                        ("MOUNTAIN" "MTN" "MNTAIN" "MNTN")
                                        ("VALLEY" "VLY" "VLLY")
                                        ("GROVE" "GRV" "GROV")
                                        ("GARDEN" "GDN" "GRDN" "GARDN")
                                        ("CREEK" "CRK" "CR")
                                        ("BROOK" "BRK")
                                        ("SHORE" "SHR" "SHORE.")
                                        ("HEIGHTS" "HTS" "HGTS" "HEIGHT")
                                        ("MEADOW" "MDW" "MDWS")
                                        ("FOREST" "FRST")
                                        ("COVE" "CV")
                                        ("SPRING" "SPG" "SPNG" "SPRNG")
                                        ("SPRINGS" "SPGS" "SPNGS" "SPRNGS")
                                        ("ESTATE" "EST")
                                        ("ISLAND" "IS" "ISL" "ISLD")
                                        ("ISLANDS" "ISS" "ISLS" "ISLNDS")
                                        ("VIEW" "VW" "VUE")
                                        ("POINT" "PT")
                                        ("CAMP" "CP" "CMP")
                                        ("HARBOR" "HBR" "HARBR" "HRBOR")
                                        ("FIELD" "FLD")
                                        ("FALLS" "FLS" "FALL")
                                        ("RANCH" "RNCH" "RANCHES" "RCH")
                                        ("PATH" "PATH" "PT" "PTH")
                                        ("LOOP" "LOOP" "LP")
                                        ("TRACE" "TRCE")
                                        ("TRACK" "TRAK")
                                        ("LANDING" "LNDG" "LNDNG")
                                        ("SUMMIT" "SMT" "SUMMT")
                                        ("GATEWAY" "GTWY" "GTWAY" "GATEWY")
                                        ("COMMON" "CMN")
                                        ("BYPASS" "BYP" "BYPAS")
                                        ("EXTENSION" "EXT" "EXTN" "EXTNSN")
                                        ("MISSION" "MSN" "MISSN")
                                        ("PRAIRIE" "PR" "PRR" "PRAIR")
                                        ("HAVEN" "HVN")
                                        ("VILLAGE" "VLG" "VILL" "VILLG" "VILLAG")
                                        ("VILLAGES" "VLGS" "VILLGS")
                                        ("WOODS" "WDS" "WOOD" "WD")
                                        ("CANYON" "CYN" "CANYN" "CNON")
                                        ("BLUFF" "BLF" "BLUFFS" "BLFS")
                                        ("ESTATES" "EST" "ESTS")
                                        ("PARK" "PARK" "PK")
                                        ("PLAINS" "PLNS" "PLN" "PLAIN")
                                        ("TUNNEL" "TUNL" "TUNNL")
                                        ("MANOR" "MNR")
                                        ("CAMPUS" "CMPS")
                                        ("CRESCENT" "CRES" "CRSNT" "CRS")
                                        ("HOLLOW" "HOLW" "HLLW")
                                        ("SHORES" "SHRS")
                                        ("HARBORS" "HBRS")
                                        ("KNOLL" "KNL")
                                        ("MILL" "ML")
                                        ("RAPIDS" "RPDS" "RAPID")
                                        ("VISTA" "VIS" "VST" "VSTA")
                                        ("COUNTY ROAD" "CR")
                                        ("COUNTY" "CNTY")

                                        ;; Directional abbreviations and variants
                                        ("NORTH" "N" "NRTH")
                                        ("SOUTH" "S" "STH")
                                        ("EAST" "E" "EST")
                                        ("WEST" "W" "WST")
                                        ("NORTHEAST" "NE")
                                        ("NORTHWEST" "NW")
                                        ("SOUTHEAST" "SE")
                                        ("SOUTHWEST" "SW")

                                        ;; Secondary-unit designators (apartments, suites, etc.)
                                        ("APARTMENT" "APT" "APART" "APMT")
                                        ("BUILDING" "BLDG" "BLD" "BLDNG")
                                        ("SUITE" "STE" "ST" "SUT")
                                        ("UNIT" "UNT" "UNI" "UN")
                                        ("ROOM" "RM")
                                        ("FLOOR" "FL" "FLR")
                                        ("DEPARTMENT" "DEPT")
                                        ("HANGAR" "HNGR" "HANG")
                                        ("LOT" "LT")
                                        ("PIER" "PR")
                                        ("SLIP" "SLP")
                                        ("SPACE" "SPC")
                                        ("STOP" "STP")
                                        ("TRAILER" "TRLR")
                                        ("OFFICE" "OFC" "OFF" "OFFC"))
  :test #'equalp)

